### ISSUE TITLE
prefering dplyr verbs as much as possible

### ISSUE THREAD

**Issue by alperyilmaz** [andrewGhazi/tidy_overview#1]
instead of using `diff` as in [here](https://github.com/andrewGhazi/tidy_overview/blob/32475d64c9d0f3e80c867e0522af365cf980db96/tidy_overview.Rmd#L517) wouldn't be better to use 

```R
mutate(new_deaths = deaths - lag(deaths, default=0)) 
```
`default` option will prevent `NA` case for the first element.

**Comment by andrewGhazi** [comment]
Yes, that would definitely be a good way to do it. I'm not sure that `default=0` is ideal since theoretically some location could report deaths on the first day, but I haven't checked if that ever happens.

I personally haven't gotten in the habit of using `lag()` and many of the more obscure dplyr functions. I didn't want to get into this during the presentation but the tidyverse contains a huge number of small helper functions of varying usefulness. So if you run into a situation where you think "I bet someone else has solved this issue before", it's a good ideal to do a Google search and check if someone has. But I also wanted to demonstrate "running into a problem" during the slides just to show that things don't always go super smoothly.
